api = "0.7"

[buildpack]
id = "dev.knative-extensions.go"
version = "0.0.6"
name = "Go Function Buildpack"

[[stacks]]
id = "io.paketo.stacks.tiny"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "io.buildpacks.stacks.jammy"

[[stacks]]
id = "io.buildpacks.stacks.jammy.tiny"
