api = "0.2"

[buildpack]
id = "dev.knative-sandbox.go"
version = "0.0.4"
name = "Go Function Buildpack"

[[stacks]]
id = "io.paketo.stacks.tiny"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "io.buildpacks.stacks.jammy"
