[[buildpacks]]
uri = "../../buildpacks/go"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/go-dist:2.3.5"
  version = "2.3.5"

[[order]]
  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    version = "2.3.5"

  [[order.group]]
    id = "dev.knative-sandbox.go"
    version = "0.0.4"

[stack]
  build-image = "docker.io/paketobuildpacks/build:1.3.167-full-cnb"
  id = "io.buildpacks.stacks.bionic"
  run-image = "index.docker.io/paketobuildpacks/run:full-cnb"
  run-image-mirrors = ["gcr.io/paketo-buildpacks/run:full-cnb"]
