[[buildpacks]]
uri = "../../buildpacks/go"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/go-dist:0.8.2"
  version = "0.8.2"

[[order]]
  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    version = "0.8.2"

  [[order.group]]
    id = "dev.knative-sandbox.go"

[stack]
  build-image = "docker.io/paketobuildpacks/build:1.3.10-full-cnb"
  id = "io.buildpacks.stacks.bionic"
  run-image = "index.docker.io/paketobuildpacks/run:full-cnb"
  run-image-mirrors = ["gcr.io/paketo-buildpacks/run:full-cnb"]
