[[buildpacks]]
uri = "../../buildpacks/go"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/go-dist:2.3.5"
  version = "2.3.5"

[[order]]
  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    version = "2.3.5"

  [[order.group]]
    id = "dev.knative-sandbox.go"
    version = "0.0.5"

[stack]
  id = "io.buildpacks.stacks.jammy.tiny"
  build-image = "index.docker.io/paketobuildpacks/build-jammy-tiny:0.1.70"
  run-image = "index.docker.io/paketobuildpacks/run-jammy-tiny:latest"
  run-image-mirrors = ["gcr.io/paketo-buildpacks/run-jammy-tiny:latest"]
